#!/bin/sh
# mvpics

VERSION='0.9.0'

mvpics_main() {
	scriptpath="$( realpath "$0" )"
	scriptname="$( basename "$scriptpath" )"

	e_args=16
	e_missing_app=17

	date_folders=0

	while getopts dhv opt
	do
		case "$opt" in
			d) date_folders=1 ;;
			h) cmd=help ;;
			v) cmd=version ;;
			*) _invalid_opt ;;
		esac
	done

	shift "$(( OPTIND - 1 ))"

	[ -z "$cmd" ] && cmd="process"

	case "$cmd" in
		help|process|version) "mvpics_$cmd" "$@" ;;
		*) _invalid_cmd ;;
	esac

	return $?
}

mvpics_process() {
	[ $# -eq 0 ] && mvpics_usage && return
	[ $# -lt 2 ] && _fatal $e_args "Must specify both source and destination."

	_require_exiftool

	src="$1"
	dst="$2"
	pattern="$dst/%Y/%Y-%m"

	[ $date_folders -ne 0 ] && pattern="$pattern/%Y%m%d"

	pattern="$pattern/%Y%m%d-%H%M%S_%%f.%%e"

	exiftool \
		'-FileName<CreateDate' \
		-progress \
		-d "$pattern" \
		-r "$src" \
		;
}

mvpics_help() {
cat <<HELP
$scriptname $VERSION

Usage: $scriptname [options] src dst

Move photos from memory card and transfer them into dated folders.

Meant to be used to transfer photos with EXIF data into a DCIM
directory of a memory card into dated folders on another volume
(e.g. Pictures/2022/2022-01/20220101-160224_DSC_0296.NEF).

Requires exiftool.

Available options:

	-d        Categorize files into date folders as well,
	          not just years and months.

	-h        Show this help screen.

	-v        Show version.

HELP
}

mvpics_version() {
	echo "$scriptname $VERSION"
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_fatal() {
	exit_code="$1"
	shift
	_error "$@"
	exit "$exit_code"
}

_invalid_cmd() {
	_error "Invalid command: $cmd"
	_echo
	mvpics_usage
	exit $e_args
}

_invalid_opt() {
	_error "Invalid option: $opt"
	_echo
	mvpics_usage
	exit $e_args
}

_require_exiftool() {
	which exiftool > /dev/null 2>&1 && return
	_fatal $e_missing_app "Missing exiftool."
}

mvpics_main "$@"
