#!/bin/sh
# mvpics
# 2022-07-08 22:37:23 JST

mvpics_main() {
	scriptpath="` realpath "$0" `"  
	scriptname="` basename "$scriptpath" `"
	scriptdir="` dirname "$scriptpath" `"

	e_args=16
	e_missing_app=17

	while getopts h opt
	do
		case $opt in
			h) mvpics_usage && return ;;
			*) _invalid_opt ;;
		esac
	done

	shift ` expr $OPTIND - 1 `

	[ -z "$cmd" ] && cmd="process"

	case "$cmd" in
		process) "mvpics_$cmd" "$@" ;;
		help|usage) mvpics_usage ;;
		*) _invalid_cmd ;;
	esac

	return $?
}

mvpics_process() {
	[ $# -eq 0 ] && mvpics_usage && return
	[ $# -lt 2 ] && _fatal $e_args "Must specify both source and destination."

	_require_exiftool

	src="$1"
	dst="$2"

	exiftool \
		'-FileName<CreateDate' \
		-progress \
		-d "$dst/%Y/%Y-%m/%Y%m%d-%H%M%S_%%f.%%e" \
		-r "$src" \
		;
}

mvpics_usage() {
cat <<USAGE
Usage: $scriptname [options] src dst

Move photos from memory card and transfer them into dated folders.

Meant to be used to transfer photos with EXIF data into a DCIM
directory of a memory card into dated folders on another volume
(e.g. Pictures/2022/2022-01/20220101-160224_DSC_0296.NEF).

Requires exiftool.

Available options:

	-h        Show this help screen.

USAGE
}

_echo() {
	echo "$@"
}

_error() {
	_echo "$@" >&2
}

_fatal() {
	local exit_code
	exit_code="$1"
	shift
	_error "$@"
	exit "$exit_code"
}

_invalid_cmd() {
	_error "Invalid command: $cmd"
	_echo
	mvpics_usage
	exit $e_args
}

_invalid_opt() {
	_error "Invalid option: $opt"
	_echo
	mvpics_usage
	exit $e_args
}

_require_exiftool() {
	which exiftool 2>&1 > /dev/null && return
	_fatal $e_missing_app "Missing exiftool."
}

mvpics_main "$@"
